"""initial users and loan_applications

Revision ID: 786e362988d9
Revises: 
Create Date: 2026-04-12 02:24:52.796074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786e362988d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arn', sa.String(length=64), nullable=False),
    sa.Column('borrower_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('pan_last_four', sa.String(length=4), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('employment_type', sa.String(length=64), nullable=False),
    sa.Column('monthly_income_inr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('requested_amount_inr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_tier', sa.String(length=32), nullable=True),
    sa.Column('default_probability', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('shap_explanation', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_applications_arn'), ['arn'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_applications_arn'))

    op.drop_table('loan_applications')
    # ### end Alembic commands ###
